### ISSUE TITLE
push readme to npm

### ISSUE THREAD

**Issue by jbolda** [jbolda/covector#126]
Currently the readme is only at the root. This means that the packages published on npm appear to have no related docs. The sub-packages can be left without a readme for the time being, but the main package needs, at the very least, the root readme copied over before publish.

**Comment by minkimcello** [comment]
I think we can close this?

**Comment by jbolda** [comment]
Yep! Thanks. It was closed in the publish in https://github.com/jbolda/covector/pull/125.
