### ISSUE TITLE
if version bump type wrong, error is not clear

### ISSUE THREAD

**Issue by nothingismagick** [jbolda/covector#132]
![image](https://user-images.githubusercontent.com/35242872/104565282-57794280-564c-11eb-9983-6a6d1ef96cc6.png)

```
---
"iota-stronghold": client
---
```

https://github.com/iotaledger/stronghold.rs/runs/1700593769?check_suite_focus=true#step:5:70

**Comment by nothingismagick** [comment]
I feel like this should have thrown before a merge was possible. A sanity check during a merge to dev would save sanity.

**Comment by jbolda** [comment]
Agreed. We should validate that the option noted is valid.
