### ISSUE TITLE
Covector should handle packages that doesn't exist on NPM yet

### ISSUE THREAD

**Issue by lucasfernog** [jbolda/covector#152]
Currently the `version-or-publish` step crashes when getting the package version from NPM if the package isn't published yet. Should we recommend users to publish an empty 0.0.0 version? Or handle it in the code?

**Comment by jbolda** [comment]
It seems like we might want to long-term provide a command that helps to detect this kind of issue. It seems like in the near term that suggesting an empty `0.0.0` package publish in the documentation may be the best route.

**Comment by jbolda** [comment]
We have added the `use` option in #280. It sets some presets one of which does a `fetch` and handles the various cases more directly, including this one.
