### ISSUE TITLE
Rearranging the default commands

### ISSUE THREAD

**Issue by minkimcello** [jbolda/covector#166]
1. The `publish` command is in the `else` block which means running `yarn covector beep` or making a typo on a different command will resort to running publish. So I think that command should also be explicit.

2. The default command (if no command is specified) will run `covector status`. From the perspective of someone who just installed `covector`, seeing `There are no changes` output to the console is not very helpful. So I think `!command` should run `yarn covector help`.

**Comment by jbolda** [comment]
1. This was originally done with the expectation that you could specify any arbitrary function that could be run. This would allow someone to have multiple types of publishes. This was a really advanced use case though and hasn't seemed to be deeply needed (yet). That is also part of the reason that it was never really documented.
2. Hmm, that is a fair point. You want to instill trust for someone just getting into it and running "status" might unintentionally scare someone that it is doing something (especially if it hasn't been `init` yet).

It feels like with these comments that it would be best to focus on the onboarding and easing someone into it. These advanced use cases should have strong guardrails and be explicitly exposed via an opt-in. I think your conclusions are sound, and would be good changes to make here.
