### ISSUE TITLE
v1 & v1.0 tags shouldn't be created on release

### ISSUE THREAD

**Issue by nothingismagick** [jbolda/covector#190]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/35242872/114789528-8b671f80-9d83-11eb-88ef-53cc7d2aefa3.png">

**Comment by jbolda** [comment]
(For others context, this is part of the `config.json` in Tauri.)

Should we maybe include the prerelease identifier appended to the tag if it's used? I believe that would alleviate the concern here.

**Comment by jbolda** [comment]
Closing as this was added as part of the `config.json` and does not specifically require covector functionality.
