### ISSUE TITLE
comments in Cargo.toml being purged

### ISSUE THREAD

**Issue by nothingismagick** [jbolda/covector#194]
When running covector, it seems that comments in toml files are being pruned.

**Comment by jbolda** [comment]
This is an issue upstream in https://github.com/tauri-apps/tauri-toml. We should probably confirm that the fixes there have been addressed in the original https://github.com/iarna/iarna-toml and switch back to that if appropriate. (`tauri-toml` was forked to add support for inline objects which Rust/cargo allows as an option when specifying a dependency version.)

/cc @lucasfernog, have you looked into it?

**Comment by jbolda** [comment]
Considering if we can address this via #236.

**Comment by amrbashir** [comment]
Just checked `iarna-toml` and unfortunately this has not been resolved upstream yet https://github.com/iarna/iarna-toml/issues/42.

I think we shouldn't wait for upstream and instead build a NAPI module using `napi-rs` that delegates the work to `toml-edit` crate which preserves the comments. I can help setting this up if approved.

**Comment by jbolda** [comment]
Closed by #303 and published in #300.
