### ISSUE TITLE
Same commit and PR links are used for every items in a release note

### ISSUE THREAD

**Issue by rhysd** [jbolda/covector#305]
Hi, wry crate is using covector and I noticed the release notes generated by covector seemed wrong.

https://github.com/tauri-apps/wry/releases

Screenshot of example:

<img width="877" alt="image" src="https://github.com/jbolda/covector/assets/823277/8b8a3040-b924-4036-96b2-ced3e838cb85">

All items in a single release have the same commit and PR links wrongly (`8646120` and `#1159` in the screenshot). FWIW, the first time I saw this issue was the release of wry v35.0 (published on Nov 21, 2023): https://github.com/tauri-apps/wry/pull/1054

The workflow is here: https://github.com/tauri-apps/wry/blob/dev/.github/workflows/covector-version-or-publish.yml

**Comment by jbolda** [comment]
Ah, I thought I had responded to this. Amr asked me as well. This is likely related to the "depth" of the git checkout. If you only checkout the last commit, it will only show that commit. In `actions/checkout`, there is a `depth` option which we typically recommend setting to `0`. Going to leave this open to make certain we confirm the docs here are clear about this.

**Comment by rhysd** [comment]
Thank you for your response! And now wry doesn't have this issue. So I guess wry has fixed the depth issue yet. Closing.
